apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-6suh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-6suh
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-6suh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-6suh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-6suh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lkxf-tenant/nodejs-users/simple-nodejs-app-6suh@sha256:591c986bf0d47db92a098685daa19863c6e6fe7efd999fff750867538d6042af
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
