apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: simple-nodejs-app-6suh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lkxf-tenant/nodejs-users/simple-nodejs-app-6suh@sha256:591c986bf0d47db92a098685daa19863c6e6fe7efd999fff750867538d6042af
        name: my-nodejs
        resources: {}
status: {}
